version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries: '*'
    open-pull-requests-limit: 2
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Australia/Melbourne'
    labels:
      - dependencies
      # Prevents `pr_branch_updater` workflow from updating
      # PR branches created by dependabot. Label name must match
      # the SKIP_UPDATE_LABEL environment
      - skipupdate

registries:
  # Allow version updates from private github npm registry
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_TOKEN }}
