tapendium-aliases:
  common: &common
    - &setup-tools
      tapendium/tap-ci-utils#v0.10.1:
        setup:
          working_dir: .

    - &secret-npm
      tapendium/1password-secrets#v2.3.0:
        file:
          - path: .npmrc-publish.tpl
            out: .npmrc

    - &npm-cache
      nienbo/cache#v2.4.15:
        id: testcontainers-dynamodb
        key: >
          "v1-{{id}}-{{runner.os}}-{{checksum 'package-lock.json'}}"
        backend: s3
        s3:
          bucket: tap-buildkite-cache
          save-cache: true
        paths:
          - node_modules
        pipeline-slug-override: testcontainers-dynamodb

steps:
  - label: ':npm: Publish package to NPM registry'
    branches: main
    plugins: *common
    commands:
      - publish-npm-package -r
